import enum

class Move(enum.Enum):
	NONE, \
	Pound, \
	KarateChop, \
	DoubleSlap, \
	CometPunch, \
	MegaPunch, \
	PayDay, \
	FirePunch, \
	IcePunch, \
	ThunderPunch, \
	Scratch, \
	ViceGrip, \
	Guillotine, \
	RazorWind, \
	SwordsDance, \
	Cut, \
	Gust, \
	WingAttack, \
	Whirlwind, \
	Fly, \
	Bind, \
	Slam, \
	VineWhip, \
	Stomp, \
	DoubleKick, \
	MegaKick, \
	JumpKick, \
	RollingKick, \
	SandAttack, \
	Headbutt, \
	HornAttack, \
	FuryAttack, \
	HornDrill, \
	Tackle, \
	BodySlam, \
	Wrap, \
	TakeDown, \
	Thrash, \
	DoubleEdge, \
	TailWhip, \
	PoisonSting, \
	Twineedle, \
	PinMissile, \
	Leer, \
	Bite, \
	Growl, \
	Roar, \
	Sing, \
	Supersonic, \
	SonicBoom, \
	Disable, \
	Acid, \
	Ember, \
	Flamethrower, \
	Mist, \
	WaterGun, \
	HydroPump, \
	Surf, \
	IceBeam, \
	Blizzard, \
	Psybeam, \
	BubbleBeam, \
	AuroraBeam, \
	HyperBeam, \
	Peck, \
	DrillPeck, \
	Submission, \
	LowKick, \
	Counter, \
	SeismicToss, \
	Strength, \
	Absorb, \
	MegaDrain, \
	LeechSeed, \
	Growth, \
	RazorLeaf, \
	SolarBeam, \
	PoisonPowder, \
	StunSpore, \
	SleepPowder, \
	PetalDance, \
	StringShot, \
	DragonRage, \
	FireSpin, \
	ThunderShock, \
	Thunderbolt, \
	ThunderWave, \
	Thunder, \
	RockThrow, \
	Earthquake, \
	Fissure, \
	Dig, \
	Toxic, \
	Confusion, \
	Psychic, \
	Hypnosis, \
	Meditate, \
	Agility, \
	QuickAttack, \
	Rage, \
	Teleport, \
	NightShade, \
	Mimic, \
	Screech, \
	DoubleTeam, \
	Recover, \
	Harden, \
	Minimize, \
	Smokescreen, \
	ConfuseRay, \
	Withdraw, \
	DefenseCurl, \
	Barrier, \
	LightScreen, \
	Haze, \
	Reflect, \
	FocusEnergy, \
	Bide, \
	Metronome, \
	MirrorMove, \
	SelfDestruct, \
	EggBomb, \
	Lick, \
	Smog, \
	Sludge, \
	BoneClub, \
	FireBlast, \
	Waterfall, \
	Clamp, \
	Swift, \
	SkullBash, \
	SpikeCannon, \
	Constrict, \
	Amnesia, \
	Kinesis, \
	SoftBoiled, \
	HighJumpKick, \
	Glare, \
	DreamEater, \
	PoisonGas, \
	Barrage, \
	LeechLife, \
	LovelyKiss, \
	SkyAttack, \
	Transform, \
	Bubble, \
	DizzyPunch, \
	Spore, \
	Flash, \
	Psywave, \
	Splash, \
	AcidArmor, \
	Crabhammer, \
	Explosion, \
	FurySwipes, \
	Bonemerang, \
	Rest, \
	RockSlide, \
	HyperFang, \
	Sharpen, \
	Conversion, \
	TriAttack, \
	SuperFang, \
	Slash, \
	Substitute, \
	Struggle = range(166)

pp_for_move = {
	Move.NONE: 0,
	Move.Pound: 35,
	Move.KarateChop: 25,
	Move.DoubleSlap: 10,
	Move.CometPunch: 15,
	Move.MegaPunch: 20,
	Move.PayDay: 20,
	Move.FirePunch: 15,
	Move.IcePunch: 15,
	Move.ThunderPunch: 15,
	Move.Scratch: 35,
	Move.ViceGrip: 30,
	Move.Guillotine: 5,
	Move.RazorWind: 10,
	Move.SwordsDance: 30,
	Move.Cut: 30,
	Move.Gust: 35,
	Move.WingAttack: 35,
	Move.Whirlwind: 20,
	Move.Fly: 15,
	Move.Bind: 20,
	Move.Slam: 20,
	Move.VineWhip: 25,
	Move.Stomp: 20,
	Move.DoubleKick: 30,
	Move.MegaKick: 5,
	Move.JumpKick: 25,
	Move.RollingKick: 15,
	Move.SandAttack: 15,
	Move.Headbutt: 15,
	Move.HornAttack: 25,
	Move.FuryAttack: 20,
	Move.HornDrill: 5,
	Move.Tackle: 35,
	Move.BodySlam: 15,
	Move.Wrap: 20,
	Move.TakeDown: 20,
	Move.Thrash: 20,
	Move.DoubleEdge: 15,
	Move.TailWhip: 30,
	Move.PoisonSting: 35,
	Move.Twineedle: 20,
	Move.PinMissile: 20,
	Move.Leer: 30,
	Move.Bite: 25,
	Move.Growl: 40,
	Move.Roar: 20,
	Move.Sing: 15,
	Move.Supersonic: 20,
	Move.SonicBoom: 20,
	Move.Disable: 20,
	Move.Acid: 30,
	Move.Ember: 25,
	Move.Flamethrower: 15,
	Move.Mist: 30,
	Move.WaterGun: 25,
	Move.HydroPump: 5,
	Move.Surf: 15,
	Move.IceBeam: 10,
	Move.Blizzard: 5,
	Move.Psybeam: 20,
	Move.BubbleBeam: 20,
	Move.AuroraBeam: 20,
	Move.HyperBeam: 5,
	Move.Peck: 35,
	Move.DrillPeck: 20,
	Move.Submission: 25,
	Move.LowKick: 20,
	Move.Counter: 20,
	Move.SeismicToss: 20,
	Move.Strength: 15,
	Move.Absorb: 20,
	Move.MegaDrain: 10,
	Move.LeechSeed: 10,
	Move.Growth: 40,
	Move.RazorLeaf: 25,
	Move.SolarBeam: 10,
	Move.PoisonPowder: 35,
	Move.StunSpore: 30,
	Move.SleepPowder: 15,
	Move.PetalDance: 20,
	Move.StringShot: 40,
	Move.DragonRage: 10,
	Move.FireSpin: 15,
	Move.ThunderShock: 30,
	Move.Thunderbolt: 15,
	Move.ThunderWave: 20,
	Move.Thunder: 10,
	Move.RockThrow: 15,
	Move.Earthquake: 10,
	Move.Fissure: 5,
	Move.Dig: 10,
	Move.Toxic: 10,
	Move.Confusion: 25,
	Move.Psychic: 10,
	Move.Hypnosis: 20,
	Move.Meditate: 40,
	Move.Agility: 30,
	Move.QuickAttack: 30,
	Move.Rage: 20,
	Move.Teleport: 20,
	Move.NightShade: 15,
	Move.Mimic: 10,
	Move.Screech: 40,
	Move.DoubleTeam: 15,
	Move.Recover: 20,
	Move.Harden: 30,
	Move.Minimize: 20,
	Move.Smokescreen: 20,
	Move.ConfuseRay: 10,
	Move.Withdraw: 40,
	Move.DefenseCurl: 40,
	Move.Barrier: 30,
	Move.LightScreen: 30,
	Move.Haze: 30,
	Move.Reflect: 20,
	Move.FocusEnergy: 30,
	Move.Bide: 10,
	Move.Metronome: 10,
	Move.MirrorMove: 20,
	Move.SelfDestruct: 5,
	Move.EggBomb: 10,
	Move.Lick: 30,
	Move.Smog: 20,
	Move.Sludge: 20,
	Move.BoneClub: 20,
	Move.FireBlast: 5,
	Move.Waterfall: 15,
	Move.Clamp: 10,
	Move.Swift: 20,
	Move.SkullBash: 15,
	Move.SpikeCannon: 15,
	Move.Constrict: 35,
	Move.Amnesia: 20,
	Move.Kinesis: 15,
	Move.SoftBoiled: 10,
	Move.HighJumpKick: 20,
	Move.Glare: 30,
	Move.DreamEater: 15,
	Move.PoisonGas: 40,
	Move.Barrage: 20,
	Move.LeechLife: 15,
	Move.LovelyKiss: 10,
	Move.SkyAttack: 5,
	Move.Transform: 10,
	Move.Bubble: 30,
	Move.DizzyPunch: 10,
	Move.Spore: 15,
	Move.Flash: 20,
	Move.Psywave: 15,
	Move.Splash: 40,
	Move.AcidArmor: 40,
	Move.Crabhammer: 10,
	Move.Explosion: 5,
	Move.FurySwipes: 15,
	Move.Bonemerang: 10,
	Move.Rest: 10,
	Move.RockSlide: 10,
	Move.HyperFang: 15,
	Move.Sharpen: 30,
	Move.Conversion: 30,
	Move.TriAttack: 10,
	Move.SuperFang: 10,
	Move.Slash: 20,
	Move.Substitute: 10,
	Move.Struggle: 10
}
